name: DemoNewCd
on: 
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, word!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'menu-online-orpin.vercel.app'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy, word!

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'menu-online-orpin.vercel.app'
    needs:  deploy-dev
    steps:
      - name: Run a one-line script
        run: echo Deploy, word!

  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'menu-online-orpin.vercel.app'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo Deploy, word!
